name: Build and Push Docker Image to AWS ECR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1  # Change to your AWS region

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 084375590547.dkr.ecr.eu-north-1.amazonaws.com
      - name: Build and Tag Docker Image
        run: |
          docker build -t mern-app .
          docker tag mern-app:latest 084375590547.dkr.ecr.eu-north-1.amazonaws.com/mern-app:latest

      - name: Push Docker Image to ECR
        run: |
          docker push 084375590547.dkr.ecr.eu-north-1.amazonaws.com/mern-app:latest
