name: Deploy MERN App to AWS ECR

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Login to AWS ECR
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 084375590547.dkr.ecr.eu-north-1.amazonaws.com

      # Build and push the backend Docker image
      - name: Build and Push Backend Image
        run: |
          docker build -t backend-app ./backend
          docker tag backend-app:latest 084375590547.dkr.ecr.eu-north-1.amazonaws.com/mern-app-backend:latest
          docker push 084375590547.dkr.ecr.eu-north-1.amazonaws.com/mern-app-backend:latest

      # Build and push the frontend Docker image
      - name: Build and Push Frontend Image
        run: |
          docker build -t frontend-app ./frontend
          docker tag frontend-app:latest 084375590547.dkr.ecr.eu-north-1.amazonaws.com/mern-app-frontend:latest
          docker push 084375590547.dkr.ecr.eu-north-1.amazonaws.com/mern-app-frontend:latest
